// AUTO-GENERATED by scripts/gen-templates.mjs — do not edit by hand.
// Run `npm run gen:templates` after changing anything under templates/.
import type { Template } from "./types";

export const TEMPLATES: Record<string, Template> = {
  "express-api": {
    "manifest": {
      "id": "express-api",
      "label": "Express API (Node.js)",
      "framework": "express",
      "description": "A minimal Express REST API with a health route and a sample resource. JSON in, JSON out.",
      "keywords": [
        "express",
        "node",
        "nodejs",
        "api",
        "backend",
        "rest",
        "service",
        "endpoint",
        "server",
        "crud",
        "javascript"
      ],
      "notesBlurb": "Scaffolded from the Express API (Node.js) template. package.json + index.js exist with a health route and a sample /api/items resource. read_file index.js, then CUSTOMIZE — add routes, middleware, and a database. Do NOT recreate the boilerplate or re-pick a stack.",
      "cli": "overlay-only"
    },
    "files": [
      {
        "path": ".gitignore",
        "content": "node_modules\n.env\n.env*.local\n.DS_Store\nnpm-debug.log*\n"
      },
      {
        "path": "index.js",
        "content": "// A minimal Express REST API. Run: npm install && npm start\nimport express from \"express\";\n\nconst app = express();\napp.use(express.json());\n\n// In-memory sample store. Replace with a real database.\nconst items = [\n  { id: 1, name: \"First item\" },\n  { id: 2, name: \"Second item\" },\n];\n\napp.get(\"/health\", (_req, res) => {\n  res.json({ status: \"ok\" });\n});\n\napp.get(\"/api/items\", (_req, res) => {\n  res.json(items);\n});\n\napp.post(\"/api/items\", (req, res) => {\n  const name = (req.body?.name ?? \"\").trim();\n  if (!name) return res.status(400).json({ error: \"name is required\" });\n  const item = { id: items.length ? items[items.length - 1].id + 1 : 1, name };\n  items.push(item);\n  res.status(201).json(item);\n});\n\nconst port = process.env.PORT || 3000;\napp.listen(port, () => console.log(`API listening on http://localhost:${port}`));\n"
      },
      {
        "path": "package.json",
        "content": "{\n  \"name\": \"express-api\",\n  \"version\": \"0.1.0\",\n  \"private\": true,\n  \"type\": \"module\",\n  \"scripts\": {\n    \"start\": \"node index.js\",\n    \"dev\": \"node --watch index.js\"\n  },\n  \"dependencies\": {\n    \"express\": \"^4.21.2\"\n  }\n}\n"
      },
      {
        "path": "README.md",
        "content": "# Express API\n\nA minimal Express REST API starter.\n\n## Run\n\n```bash\nnpm install\nnpm start\n```\n\n- `GET /health` → `{ \"status\": \"ok\" }`\n- `GET /api/items` → list items\n- `POST /api/items` `{ \"name\": \"...\" }` → create an item\n\nReplace the in-memory store in `index.js` with a real database when you're ready.\n"
      }
    ]
  },
  "flask-api": {
    "manifest": {
      "id": "flask-api",
      "label": "Flask API (Python)",
      "framework": "flask",
      "description": "A minimal Flask REST API with a health route and a sample resource. JSON in, JSON out.",
      "keywords": [
        "flask",
        "python",
        "api",
        "backend",
        "rest",
        "service",
        "endpoint",
        "server",
        "crud",
        "microservice"
      ],
      "notesBlurb": "Scaffolded from the Flask API (Python) template. app.py + requirements.txt exist with a health route and a sample /api/items resource. read_file app.py, then CUSTOMIZE — add routes, models, and logic. Do NOT recreate the boilerplate or re-pick a stack.",
      "cli": "overlay-only"
    },
    "files": [
      {
        "path": ".gitignore",
        "content": "__pycache__/\n*.pyc\n.venv/\nvenv/\n.env\ninstance/\n"
      },
      {
        "path": "app.py",
        "content": "\"\"\"A minimal Flask REST API. Run: pip install -r requirements.txt && flask run.\"\"\"\nfrom flask import Flask, jsonify, request\n\napp = Flask(__name__)\n\n# In-memory sample store. Replace with a real database (SQLAlchemy, etc.).\nitems = [\n    {\"id\": 1, \"name\": \"First item\"},\n    {\"id\": 2, \"name\": \"Second item\"},\n]\n\n\n@app.get(\"/health\")\ndef health():\n    return jsonify(status=\"ok\")\n\n\n@app.get(\"/api/items\")\ndef list_items():\n    return jsonify(items)\n\n\n@app.post(\"/api/items\")\ndef create_item():\n    data = request.get_json(silent=True) or {}\n    name = (data.get(\"name\") or \"\").strip()\n    if not name:\n        return jsonify(error=\"name is required\"), 400\n    item = {\"id\": (items[-1][\"id\"] + 1) if items else 1, \"name\": name}\n    items.append(item)\n    return jsonify(item), 201\n\n\nif __name__ == \"__main__\":\n    app.run(host=\"0.0.0.0\", port=5000, debug=True)\n"
      },
      {
        "path": "README.md",
        "content": "# Flask API\n\nA minimal Flask REST API starter.\n\n## Run\n\n```bash\npip install -r requirements.txt\nflask run\n```\n\n- `GET /health` → `{ \"status\": \"ok\" }`\n- `GET /api/items` → list items\n- `POST /api/items` `{ \"name\": \"...\" }` → create an item\n\nReplace the in-memory store in `app.py` with a real database when you're ready.\n"
      },
      {
        "path": "requirements.txt",
        "content": "Flask>=3.0,<4.0\n"
      }
    ]
  },
  "nextjs-app": {
    "manifest": {
      "id": "nextjs-app",
      "label": "Next.js app (TypeScript)",
      "framework": "next",
      "description": "Next.js App Router + TypeScript starter. Server components, a home page, and global styles.",
      "keywords": [
        "next",
        "nextjs",
        "react",
        "fullstack",
        "app",
        "dashboard",
        "saas",
        "blog",
        "web app",
        "ssr",
        "server",
        "typescript"
      ],
      "notesBlurb": "Scaffolded from the Next.js (App Router + TypeScript) template. The stack and config exist (package.json, next.config.mjs, tsconfig.json, app/layout.tsx, app/page.tsx, app/globals.css). read_file the key files, then CUSTOMIZE — add routes under app/, components, and logic. Do NOT recreate the config or re-scaffold.",
      "cli": "npx --yes create-next-app@latest . --ts --app --eslint --no-tailwind --no-src-dir --import-alias \"@/*\" --use-npm --skip-install"
    },
    "files": [
      {
        "path": ".gitignore",
        "content": "/node_modules\n/.next\n/out\n/build\nnext-env.d.ts\n*.tsbuildinfo\n.env*.local\n.DS_Store\n"
      },
      {
        "path": "app/globals.css",
        "content": ":root {\n  color-scheme: dark;\n  --bg: #0b0f1a;\n  --text: #e8edf5;\n  --muted: #9aa7bd;\n  --accent: #6d8bff;\n}\n\n* { box-sizing: border-box; }\n\nhtml, body {\n  margin: 0;\n  padding: 0;\n  background: var(--bg);\n  color: var(--text);\n  font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;\n}\n\n.main {\n  max-width: 680px;\n  margin: 0 auto;\n  padding: 96px 24px;\n}\n\n.main h1 {\n  font-size: clamp(2rem, 6vw, 3rem);\n  letter-spacing: -0.03em;\n  margin: 0 0 16px;\n}\n\n.main p { color: var(--muted); font-size: 1.1rem; line-height: 1.6; }\n\ncode {\n  background: rgba(255, 255, 255, 0.08);\n  padding: 2px 6px;\n  border-radius: 6px;\n  font-size: 0.9em;\n}\n\n.link {\n  display: inline-block;\n  margin-top: 24px;\n  color: var(--accent);\n  text-decoration: none;\n  font-weight: 600;\n}\n.link:hover { text-decoration: underline; }\n"
      },
      {
        "path": "app/layout.tsx",
        "content": "import type { Metadata } from \"next\";\nimport \"./globals.css\";\n\nexport const metadata: Metadata = {\n  title: \"Next.js App\",\n  description: \"Scaffolded with Helix\",\n};\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang=\"en\">\n      <body>{children}</body>\n    </html>\n  );\n}\n"
      },
      {
        "path": "app/page.tsx",
        "content": "export default function Home() {\n  return (\n    <main className=\"main\">\n      <h1>Your Next.js app</h1>\n      <p>\n        Edit <code>app/page.tsx</code> to get started. Add routes as folders under <code>app/</code>, drop\n        components alongside, and wire up your data.\n      </p>\n      <a className=\"link\" href=\"https://nextjs.org/docs\" target=\"_blank\" rel=\"noreferrer\">\n        Next.js docs →\n      </a>\n    </main>\n  );\n}\n"
      },
      {
        "path": "next.config.mjs",
        "content": "/** @type {import('next').NextConfig} */\nconst nextConfig = {};\n\nexport default nextConfig;\n"
      },
      {
        "path": "package.json",
        "content": "{\n  \"name\": \"nextjs-app\",\n  \"version\": \"0.1.0\",\n  \"private\": true,\n  \"scripts\": {\n    \"dev\": \"next dev\",\n    \"build\": \"next build\",\n    \"start\": \"next start\",\n    \"lint\": \"next lint\"\n  },\n  \"dependencies\": {\n    \"next\": \"^15.1.0\",\n    \"react\": \"^19.0.0\",\n    \"react-dom\": \"^19.0.0\"\n  },\n  \"devDependencies\": {\n    \"@types/node\": \"^20\",\n    \"@types/react\": \"^19\",\n    \"@types/react-dom\": \"^19\",\n    \"typescript\": \"^5\"\n  }\n}\n"
      },
      {
        "path": "tsconfig.json",
        "content": "{\n  \"compilerOptions\": {\n    \"target\": \"ES2020\",\n    \"lib\": [\"dom\", \"dom.iterable\", \"esnext\"],\n    \"allowJs\": true,\n    \"skipLibCheck\": true,\n    \"strict\": true,\n    \"noEmit\": true,\n    \"esModuleInterop\": true,\n    \"module\": \"esnext\",\n    \"moduleResolution\": \"bundler\",\n    \"resolveJsonModule\": true,\n    \"isolatedModules\": true,\n    \"jsx\": \"preserve\",\n    \"incremental\": true,\n    \"plugins\": [{ \"name\": \"next\" }],\n    \"paths\": { \"@/*\": [\"./*\"] }\n  },\n  \"include\": [\"next-env.d.ts\", \"**/*.ts\", \"**/*.tsx\", \".next/types/**/*.ts\"],\n  \"exclude\": [\"node_modules\"]\n}\n"
      }
    ]
  },
  "static-web": {
    "manifest": {
      "id": "static-web",
      "label": "Static site (HTML/CSS/JS)",
      "framework": "static",
      "description": "A single-page static site — HTML, CSS, and vanilla JS. No build step; previews instantly.",
      "keywords": [
        "landing",
        "page",
        "html",
        "static",
        "marketing",
        "brochure",
        "simple",
        "website",
        "site",
        "one-page",
        "promo"
      ],
      "notesBlurb": "Scaffolded from the Static site template: index.html + style.css + script.js, no build step. Customize these files to the user's request — do NOT recreate the HTML boilerplate or re-pick a stack.",
      "cli": "overlay-only"
    },
    "files": [
      {
        "path": "index.html",
        "content": "<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <title>My Site</title>\n    <link rel=\"stylesheet\" href=\"style.css\" />\n  </head>\n  <body>\n    <header class=\"hero\">\n      <nav class=\"nav\">\n        <span class=\"brand\">Brand</span>\n        <button id=\"cta\" class=\"btn\">Get started</button>\n      </nav>\n      <h1 class=\"title\">Build something great</h1>\n      <p class=\"subtitle\">A clean starting point for your static site. Edit the text, colors, and sections to match your idea.</p>\n    </header>\n\n    <main class=\"container\">\n      <section class=\"grid\">\n        <article class=\"card\">\n          <h2>Fast</h2>\n          <p>No build step — open and ship.</p>\n        </article>\n        <article class=\"card\">\n          <h2>Simple</h2>\n          <p>Just HTML, CSS, and a little JavaScript.</p>\n        </article>\n        <article class=\"card\">\n          <h2>Yours</h2>\n          <p>Customize every section to fit your brand.</p>\n        </article>\n      </section>\n    </main>\n\n    <footer class=\"footer\">\n      <p>&copy; <span id=\"year\"></span> Brand. Built with Helix.</p>\n    </footer>\n\n    <script src=\"script.js\"></script>\n  </body>\n</html>\n"
      },
      {
        "path": "script.js",
        "content": "// Set the footer year and wire the CTA. Replace with your own logic.\ndocument.getElementById(\"year\").textContent = new Date().getFullYear();\n\ndocument.getElementById(\"cta\").addEventListener(\"click\", () => {\n  alert(\"Hello from your new site! Edit script.js to make this do something real.\");\n});\n"
      },
      {
        "path": "style.css",
        "content": ":root {\n  --bg: #0b0f1a;\n  --panel: #131a2a;\n  --text: #e8edf5;\n  --muted: #9aa7bd;\n  --accent: #6d8bff;\n  --radius: 14px;\n}\n\n* { box-sizing: border-box; }\n\nbody {\n  margin: 0;\n  font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;\n  background: var(--bg);\n  color: var(--text);\n  line-height: 1.6;\n}\n\n.hero {\n  padding: 24px 24px 64px;\n  background: radial-gradient(1200px 400px at 50% -10%, rgba(109, 139, 255, 0.25), transparent);\n  text-align: center;\n}\n\n.nav {\n  max-width: 960px;\n  margin: 0 auto 48px;\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n}\n\n.brand { font-weight: 700; letter-spacing: -0.02em; }\n\n.title {\n  font-size: clamp(2rem, 6vw, 3.5rem);\n  margin: 0 0 12px;\n  letter-spacing: -0.03em;\n}\n\n.subtitle {\n  max-width: 620px;\n  margin: 0 auto;\n  color: var(--muted);\n  font-size: 1.1rem;\n}\n\n.container { max-width: 960px; margin: -32px auto 0; padding: 0 24px 64px; }\n\n.grid {\n  display: grid;\n  gap: 16px;\n  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));\n}\n\n.card {\n  background: var(--panel);\n  border: 1px solid rgba(255, 255, 255, 0.06);\n  border-radius: var(--radius);\n  padding: 20px;\n}\n\n.card h2 { margin: 0 0 6px; font-size: 1.15rem; }\n.card p { margin: 0; color: var(--muted); }\n\n.btn {\n  background: var(--accent);\n  color: #0b0f1a;\n  border: 0;\n  border-radius: 999px;\n  padding: 10px 18px;\n  font-weight: 600;\n  cursor: pointer;\n  transition: filter 0.15s ease;\n}\n.btn:hover { filter: brightness(1.08); }\n\n.footer {\n  border-top: 1px solid rgba(255, 255, 255, 0.06);\n  text-align: center;\n  color: var(--muted);\n  padding: 24px;\n  font-size: 0.9rem;\n}\n"
      }
    ]
  },
  "vite-spa": {
    "manifest": {
      "id": "vite-spa",
      "label": "Vite + React SPA (TypeScript)",
      "framework": "vite",
      "description": "A client-side React single-page app powered by Vite + TypeScript. Fast HMR, no server.",
      "keywords": [
        "vite",
        "react",
        "spa",
        "single page",
        "client",
        "interactive",
        "tool",
        "kanban",
        "dashboard",
        "app",
        "typescript",
        "frontend"
      ],
      "notesBlurb": "Scaffolded from the Vite + React (TypeScript) SPA template. Config exists (package.json, vite.config.ts, tsconfig.json, index.html, src/main.tsx, src/App.tsx). read_file the key files, then CUSTOMIZE src/App.tsx and add components/state. Do NOT recreate the config or re-scaffold.",
      "cli": "npm create vite@latest . -- --template react-ts"
    },
    "files": [
      {
        "path": ".gitignore",
        "content": "node_modules\ndist\ndist-ssr\n*.local\n.DS_Store\n.env*.local\n"
      },
      {
        "path": "index.html",
        "content": "<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <title>Vite + React</title>\n  </head>\n  <body>\n    <div id=\"root\"></div>\n    <script type=\"module\" src=\"/src/main.tsx\"></script>\n  </body>\n</html>\n"
      },
      {
        "path": "package.json",
        "content": "{\n  \"name\": \"vite-spa\",\n  \"private\": true,\n  \"version\": \"0.1.0\",\n  \"type\": \"module\",\n  \"scripts\": {\n    \"dev\": \"vite\",\n    \"build\": \"vite build\",\n    \"preview\": \"vite preview\"\n  },\n  \"dependencies\": {\n    \"react\": \"^19.0.0\",\n    \"react-dom\": \"^19.0.0\"\n  },\n  \"devDependencies\": {\n    \"@types/react\": \"^19\",\n    \"@types/react-dom\": \"^19\",\n    \"@vitejs/plugin-react\": \"^4.3.4\",\n    \"typescript\": \"^5\",\n    \"vite\": \"^6.0.5\"\n  }\n}\n"
      },
      {
        "path": "src/App.tsx",
        "content": "import { useState } from \"react\";\n\nexport default function App() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <main className=\"app\">\n      <h1>Vite + React</h1>\n      <p>Edit <code>src/App.tsx</code> and save to start building your app.</p>\n      <button onClick={() => setCount((c) => c + 1)}>count is {count}</button>\n    </main>\n  );\n}\n"
      },
      {
        "path": "src/index.css",
        "content": ":root {\n  color-scheme: dark;\n  font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;\n  background: #0b0f1a;\n  color: #e8edf5;\n}\n\n* { box-sizing: border-box; }\nbody { margin: 0; }\n\n.app {\n  max-width: 640px;\n  margin: 0 auto;\n  padding: 96px 24px;\n  text-align: center;\n}\n\n.app h1 {\n  font-size: clamp(2rem, 6vw, 3rem);\n  letter-spacing: -0.03em;\n  margin: 0 0 12px;\n}\n\n.app p { color: #9aa7bd; }\n\ncode {\n  background: rgba(255, 255, 255, 0.08);\n  padding: 2px 6px;\n  border-radius: 6px;\n}\n\nbutton {\n  margin-top: 24px;\n  background: #6d8bff;\n  color: #0b0f1a;\n  border: 0;\n  border-radius: 999px;\n  padding: 10px 20px;\n  font-weight: 600;\n  font-size: 1rem;\n  cursor: pointer;\n}\nbutton:hover { filter: brightness(1.08); }\n"
      },
      {
        "path": "src/main.tsx",
        "content": "import { StrictMode } from \"react\";\nimport { createRoot } from \"react-dom/client\";\nimport App from \"./App\";\nimport \"./index.css\";\n\ncreateRoot(document.getElementById(\"root\")!).render(\n  <StrictMode>\n    <App />\n  </StrictMode>,\n);\n"
      },
      {
        "path": "tsconfig.json",
        "content": "{\n  \"compilerOptions\": {\n    \"target\": \"ES2020\",\n    \"useDefineForClassFields\": true,\n    \"lib\": [\"ES2020\", \"DOM\", \"DOM.Iterable\"],\n    \"module\": \"ESNext\",\n    \"skipLibCheck\": true,\n    \"moduleResolution\": \"bundler\",\n    \"allowImportingTsExtensions\": true,\n    \"resolveJsonModule\": true,\n    \"isolatedModules\": true,\n    \"noEmit\": true,\n    \"jsx\": \"react-jsx\",\n    \"strict\": true\n  },\n  \"include\": [\"src\"]\n}\n"
      },
      {
        "path": "vite.config.ts",
        "content": "import { defineConfig } from \"vite\";\nimport react from \"@vitejs/plugin-react\";\n\nexport default defineConfig({\n  plugins: [react()],\n});\n"
      }
    ]
  }
};

export const TEMPLATE_IDS: string[] = Object.keys(TEMPLATES);
