/**
 * Bundles the AI Lab lessons (lessons/<id>/lesson.json) into a single TS module
 * (src/lib/lessons/registry.generated.ts) so they ship inside the deploy — no
 * runtime filesystem reads. Mirrors gen:templates.
 *
 * Run: npm run gen:lessons  (also runs at prebuild).
 *
 * Each lessons/<id>/lesson.json holds the manifest fields plus a `steps` array.
 * The `id` must match the folder name.
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(process.cwd(), "lessons");
const OUT = path.resolve(process.cwd(), "src/lib/lessons/registry.generated.ts");

function main() {
  const lessons = {};
  if (fs.existsSync(ROOT)) {
    const ids = fs
      .readdirSync(ROOT, { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .sort();
    for (const id of ids) {
      const file = path.join(ROOT, id, "lesson.json");
      if (!fs.existsSync(file)) {
        console.warn(`[gen-lessons] ${id}/ has no lesson.json — skipping`);
        continue;
      }
      const raw = JSON.parse(fs.readFileSync(file, "utf8"));
      if (raw.id !== id) throw new Error(`[gen-lessons] ${id}/lesson.json id="${raw.id}" must match dir`);
      const { steps, ...manifest } = raw;
      if (!Array.isArray(steps) || steps.length === 0) throw new Error(`[gen-lessons] ${id} has no steps`);
      lessons[id] = { manifest, steps };
    }
  }

  const header =
    "// AUTO-GENERATED by scripts/gen-lessons.mjs — do not edit by hand.\n" +
    "// Run `npm run gen:lessons` after changing anything under lessons/.\n" +
    'import type { Lesson } from "./types";\n\n';
  const body =
    "export const LESSONS: Record<string, Lesson> = " +
    JSON.stringify(lessons, null, 2) +
    ";\n\nexport const LESSON_IDS: string[] = Object.keys(LESSONS);\n";

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, header + body);
  console.log(`[gen-lessons] wrote ${Object.keys(lessons).length} lessons → ${path.relative(process.cwd(), OUT)}`);
}

main();
