// Bundles the architecture docs/diagrams into a TS module so the admin
// "Architecture" viewer can render them at runtime (no runtime fs, works on
// Vercel). Runs in prebuild — every push regenerates, so the in-app docs always
// match the repo. Mirrors gen-templates.mjs / gen:schema-sql.
//
// Sources:
//   docs/architecture/*.md, *.html  — curated architecture docs (md + html)
//   docs/diagrams/*.html            — existing self-contained visual diagrams
// (PDFs are skipped — too large to bundle and can't render inline.)

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const SOURCES = [
  { dir: "docs/architecture", exts: [".md", ".html"] },
  { dir: "docs/diagrams", exts: [".html"] },
];

function titleFromMd(content, file) {
  const m = content.match(/^#\s+(.+)$/m);
  return (m ? m[1] : file).replace(/[#*`]/g, "").trim();
}
function titleFromHtml(content, file) {
  const t = content.match(/<title>([^<]+)<\/title>/i) || content.match(/<h1[^>]*>([^<]+)<\/h1>/i);
  return (t ? t[1] : prettyName(file)).trim();
}
function prettyName(file) {
  return file
    .replace(/\.[^.]+$/, "")
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

const docs = [];
for (const { dir, exts } of SOURCES) {
  const abs = join(ROOT, dir);
  if (!existsSync(abs)) continue;
  for (const file of readdirSync(abs).sort()) {
    const ext = file.slice(file.lastIndexOf(".")).toLowerCase();
    if (!exts.includes(ext)) continue;
    const content = readFileSync(join(abs, file), "utf8");
    const type = ext === ".md" ? "md" : "html";
    docs.push({
      slug: `${dir.split("/").pop()}-${file.replace(/\.[^.]+$/, "")}`,
      title: type === "md" ? titleFromMd(content, file) : titleFromHtml(content, file),
      source: `${dir}/${file}`,
      type,
      content,
    });
  }
}

const out =
  "// AUTO-GENERATED by scripts/gen-docs.mjs — do not edit. Edit the source docs\n" +
  "// under docs/architecture or docs/diagrams; prebuild regenerates this.\n" +
  "export interface ArchitectureDoc {\n" +
  "  slug: string;\n  title: string;\n  source: string;\n  type: 'md' | 'html';\n  content: string;\n}\n" +
  `export const ARCHITECTURE_DOCS: ArchitectureDoc[] = ${JSON.stringify(docs, null, 2)};\n`;

writeFileSync(join(ROOT, "src/lib/architecture-docs.ts"), out);
console.log(`gen-docs: bundled ${docs.length} architecture doc(s).`);
