import "server-only";

/**
 * Turbo build — parallel leaf generation (server side).
 *
 * Each file in the manifest is generated by its OWN stateless `runOneShot`
 * call: no conversation history, no tool loop, so nothing is re-sent. Each call
 * carries only the shared contract + the file list + this file's spec. They run
 * with bounded concurrency (see runPool in ./parse), so wall-clock is
 * ~(files / concurrency) instead of the sequential loop's file-by-file hops.
 *
 * The pure helpers (buildWorkerUser, parseFileReply, runPool) live in ./parse
 * (unit-tested); this file adds the model call.
 */

import { runOneShot } from "@/lib/ai-agent";
import { buildWorkerUser, parseFileReply, type TurboManifest, type TurboFileSpec, type AiPrefs } from "./parse";

const WORKER_SYSTEM =
  "You generate EXACTLY ONE source file for a larger application, working in parallel with other workers you " +
  "cannot talk to. Output ONLY the complete contents of your file, inside a single fenced code block — no prose, " +
  "no explanation, no other files. The file must be COMPLETE and runnable (no TODOs, no placeholders), consistent " +
  "with the SHARED CONTRACT, and import sibling files exactly at the paths listed in the manifest.";

export type GeneratedFile =
  | { path: string; content: string; tokensUsed: number }
  | { path: string; error: string; tokensUsed: number };

/** Generate one file via a single stateless model call. */
export async function generateFile(
  prefs: AiPrefs,
  manifest: TurboManifest,
  spec: TurboFileSpec,
  request: string,
  notes: string | null,
): Promise<GeneratedFile> {
  const res = await runOneShot({
    provider: prefs.provider,
    model: prefs.model,
    apiKey: prefs.apiKey,
    baseUrl: prefs.baseUrl,
    extraHeaders: prefs.extraHeaders,
    system: WORKER_SYSTEM,
    user: buildWorkerUser(manifest, spec, request, notes),
    maxTokens: 16_000,
  });
  if ("error" in res) return { path: spec.path, error: res.error, tokensUsed: 0 };
  const content = parseFileReply(res.text);
  if (content == null) return { path: spec.path, error: "empty or non-code reply", tokensUsed: res.tokensUsed };
  return { path: spec.path, content, tokensUsed: res.tokensUsed };
}
