// AUTO-GENERATED by scripts/gen-lessons.mjs — do not edit by hand.
// Run `npm run gen:lessons` after changing anything under lessons/.
import type { Lesson } from "./types";

export const LESSONS: Record<string, Lesson> = {
  "data-and-features": {
    "manifest": {
      "id": "data-and-features",
      "title": "Data is everything",
      "blurb": "AI learns from data — pick the right measurements and make the first cut that separates the kinds.",
      "level": "beginner",
      "estMinutes": 10,
      "icon": "Boxes",
      "concept": "data",
      "order": 2
    },
    "steps": [
      {
        "kind": "explain",
        "title": "What data looks like",
        "body": "An AI learns from a big pile of **examples** — that's **data**, usually just a **table**. Each **row** is one example (one penguin, one photo). Each **column** is one thing we measured.\n\nTwo words pros use constantly:\n- **Features** = the things we *measure* (a penguin's bill length, flipper length…).\n- **Label** = the *answer* we want (which kind of penguin it is).\n\nThe AI's job: look at the **features** and guess the **label**."
      },
      {
        "kind": "widget",
        "widget": "dataExplorer",
        "title": "Make the first cut",
        "body": "Here are two kinds of penguin with three measurements each. Put measurements on the **X** and **Y** axes, then **drag the divider** to split the two kinds apart. Find the measurements + cut that separate them best — aim for 90%.",
        "config": {
          "dataset": "penguins"
        }
      },
      {
        "kind": "explain",
        "title": "Good features do the work",
        "body": "Notice how **some measurements separated the penguins cleanly** and others left the colors all mixed up? Picking **good features** is half the battle in real AI.\n\nIt's like guessing someone's favorite sport: their *height* helps a little, but \"do they own a soccer ball?\" helps a lot more. With the right features, a single cut already does most of the job — that's the seed of every classifier."
      },
      {
        "kind": "explain",
        "title": "Garbage in, garbage out — and bias",
        "body": "Here's the rule behind most AI failures: **an AI can only be as good as its data.** Messy or lopsided data → a confused AI.\n\nImagine training on **100 of one kind and 4 of the other**. The AI barely sees the rare kind, so it just guesses the common one — not because it's smart, but because that's mostly what it *saw*. That lopsidedness has a name: **bias**, and it comes from the data we collect, not the computer."
      },
      {
        "kind": "quiz",
        "title": "Spot the bias",
        "question": "An AI that sorts fruit was trained on 100 apples and 4 bananas. What will probably happen?",
        "choices": [
          "It works perfectly",
          "It leans toward guessing 'apple' because that's mostly what it saw",
          "It refuses to run",
          "It prefers bananas"
        ],
        "answer": 1,
        "explain": "Exactly — a lopsided dataset makes a lopsided AI. Balanced, fair examples are the fix, and that's one of the most important jobs in real AI."
      },
      {
        "kind": "explain",
        "title": "What you learned 🎉",
        "body": "- **Data** = a table of examples with **features** (what we measure) and a **label** (the answer)\n- **Good features** make the kinds separate — you found them and cut them apart yourself\n- **Garbage in, garbage out** — data quality beats computer speed\n- **Bias** is born from lopsided data; **balanced, fair data** is the cure\n\n**Next up:** instead of sorting into kinds, you'll teach an AI to **predict a number** — that's *regression*."
      }
    ]
  },
  "decision-trees": {
    "manifest": {
      "id": "decision-trees",
      "title": "Decision trees",
      "blurb": "An AI you can actually read — grow a tree of yes/no questions and watch it sort a pile of pets.",
      "level": "intermediate",
      "estMinutes": 11,
      "icon": "GitBranch",
      "concept": "trees",
      "order": 5
    },
    "steps": [
      {
        "kind": "explain",
        "title": "The AI you can read",
        "body": "Some AIs are a mystery box — they give an answer but can't explain *why*.\n\nA **decision tree** is the opposite. It sorts things with a chain of simple **yes/no questions**, like a game of 20 Questions. Each question is a **split** that cuts a pile into two. You're about to grow one yourself."
      },
      {
        "kind": "widget",
        "widget": "tree",
        "title": "Grow your tree",
        "body": "Here's a pile of pets — cats, dogs and rabbits — with their weight, ear length and tail length. **Click a leaf**, pick a measurement and a cut, and **Add split**. Keep splitting the messy leaves until your tree sorts almost all of them. Watch the accuracy climb!",
        "config": {
          "dataset": "creatures"
        }
      },
      {
        "kind": "explain",
        "title": "Look what you did",
        "body": "Notice how **one split was never enough** — you had to keep asking another question on each side, and the tree got deeper and smarter. That branching shape is exactly why it's called a *tree*.\n\nAnd each split you added split the pile a little **cleaner** — that's the whole game: a tree always hunts for the question that separates the groups best."
      },
      {
        "kind": "explain",
        "title": "Its superpower: you can explain it",
        "body": "Here's what makes trees special. If your tree says *\"this is a rabbit,\"* it can show exactly **why**: *\"because its tail was short, and it was light.\"* You can read the path.\n\nThat's called being **explainable** (a \"white box\"). Doctors, banks and judges love trees for this — when an AI affects someone's life, being able to explain the *why* really matters."
      },
      {
        "kind": "quiz",
        "title": "Why trees?",
        "question": "Why might a hospital prefer a decision tree over a mystery-box AI?",
        "choices": [
          "It's prettier",
          "You can see and explain exactly why it made each decision",
          "It needs no data",
          "It's always 100% correct"
        ],
        "answer": 1,
        "explain": "Explainability! A tree shows its reasoning step by step — crucial when a decision affects a real person."
      },
      {
        "kind": "explain",
        "title": "What you built 🎉",
        "body": "You grew a real decision tree:\n\n- It sorts things with a chain of **yes/no questions** (splits)\n- **More branches = smarter** — one split is rarely enough\n- Each split aims to separate the groups **cleanest**\n- Its superpower is being **explainable** — it can always show its reasoning\n\nWant to go deeper? The **Decision Tree Studio** has the same build with a held-out test set, so you can watch *overfitting* happen. **Next up:** neural networks — teach a tiny digital 'brain' to learn."
      }
    ]
  },
  "how-a-brain-learns": {
    "manifest": {
      "id": "how-a-brain-learns",
      "title": "How a neuron learns",
      "blurb": "Draw a line to tell cats from dogs — then watch a real neuron tune its own line until it beats you.",
      "level": "beginner",
      "estMinutes": 14,
      "icon": "Brain",
      "concept": "neural networks",
      "order": 6,
      "objectives": [
        "What a neuron really is — a line that splits things into two groups",
        "Why a line you draw by hand can't quite catch everything",
        "How a neuron fixes its own line by learning from its mistakes",
        "How to train one yourself, from scratch, on brand-new data"
      ],
      "glossary": [
        {
          "term": "Neuron",
          "def": "The tiniest part of an AI brain. With two clues it makes one call: this group or that one — by drawing a line."
        },
        {
          "term": "Decision boundary",
          "def": "The line a neuron draws. Everything on one side is one group; everything on the other side is the other."
        },
        {
          "term": "Weights",
          "def": "The numbers that tilt and slide the line. Changing the weights moves the boundary."
        },
        {
          "term": "Training",
          "def": "Doing the same thing over and over: check which dots are on the wrong side, nudge the line a little, repeat."
        },
        {
          "term": "Accuracy",
          "def": "How many it got on the right side, out of all of them. 100% means every dot is sorted correctly."
        }
      ]
    },
    "steps": [
      {
        "kind": "explain",
        "title": "A robot that sorts pets",
        "body": "Imagine a robot with one job: look at a pet and say **cat or dog**. It can't see fur or hear barks — all it gets is two clues: **how big the ears are** and **how long the tail is**.\n\nIf we put every pet on a chart — ear size going across, tail length going up — cats land in one corner and dogs in another. So here's the robot's whole trick: **draw a line** with cats on one side and dogs on the other. That line is the entire brain. Let's build it."
      },
      {
        "kind": "predict",
        "title": "First, a guess",
        "prompt": "Do you think **one straight line** could separate almost all the cats from the dogs on that chart?",
        "choices": [
          "Yes — one straight line could split most of them",
          "No — you'd need a curvy, wiggly line",
          "I'm honestly not sure yet"
        ],
        "afterPick": "Hold that thought. You're about to draw the line yourself and see what really happens. →",
        "youWillDo": "make a quick prediction"
      },
      {
        "kind": "widget",
        "widget": "neuronBoundary",
        "title": "Draw the line yourself",
        "body": "Here's the chart. **Drag the two purple dots** up and down to swing the line until cats and dogs are on different sides. Watch the **wrong** counter — get it as low as you can, then press **Lock in my line**.",
        "youWillDo": "drag the line to split cats from dogs",
        "config": {
          "phase": "explore",
          "dataset": "boundary"
        }
      },
      {
        "kind": "explain",
        "title": "So close — but not perfect",
        "body": "Notice what happened: you got *most* of them, but a few stubborn dots stayed on the wrong side no matter how you tilted the line. That's not your fault — the groups overlap a little, and a line placed **by hand** can only do so much.\n\nSo here's the real question: how could the robot do **better** than your best guess? The secret is that it doesn't guess just once. It **adjusts** — again and again. Let's watch."
      },
      {
        "kind": "widget",
        "widget": "neuronBoundary",
        "title": "Watch the neuron learn",
        "body": "This line starts out **bad on purpose**. Press **Watch it learn**. Every time a dot is on the wrong side (it flashes with a red ring), the neuron **nudges the line a tiny bit** to fix it — then checks again, and again. Watch the wrong rings disappear.",
        "youWillDo": "watch a neuron tune its own line",
        "config": {
          "phase": "reveal",
          "dataset": "boundary"
        }
      },
      {
        "kind": "explain",
        "title": "Now it has names",
        "body": "What you just watched has real names — and now they'll make sense:\n\n- The line is the **decision boundary**.\n- The numbers that tilt and slide it are the neuron's **weights**.\n- **Learning** is just this: after each mistake, nudge the weights a little so the line fits better — over and over.\n\nThat's it. That self-fixing loop *is* a neuron learning. Every AI you've heard of does this — only with a lot more dots and a lot more lines."
      },
      {
        "kind": "quiz",
        "title": "Check yourself",
        "question": "When the neuron \"learns,\" what is actually changing each round?",
        "choices": [
          "It deletes the dots it keeps getting wrong",
          "Its weights — the numbers that tilt the line",
          "The colors of the dots",
          "Nothing really changes"
        ],
        "answer": 1,
        "explain": "Right! Learning = nudging the **weights** after each mistake. The dots never change — the line does."
      },
      {
        "kind": "widget",
        "widget": "neuronBoundary",
        "title": "Your turn — train one",
        "body": "New pets, and this time **no hints**. Set a rough line with the purple dots, then press **Train my neuron** and watch it finish the job on its own.",
        "youWillDo": "train your own neuron on fresh data",
        "config": {
          "phase": "youdo",
          "dataset": "boundaryEasy"
        }
      },
      {
        "kind": "reflect",
        "title": "Make it yours",
        "prompt": "In your own words: **how does a neuron learn** to tell two groups apart?",
        "placeholder": "Like: it starts with a not-great line, then…",
        "recall": {
          "question": "A neuron starts with a line that isn't great. How does it get better?",
          "choices": [
            "It memorizes every single dot",
            "It nudges its weights a little after each mistake, over and over",
            "It throws away the dots it gets wrong",
            "It waits for a human to fix the line"
          ],
          "answer": 1,
          "explain": "Exactly — guess, see what's wrong, nudge the weights, repeat. That loop is the heartbeat of every AI."
        },
        "youWillDo": "explain it back in your own words"
      },
      {
        "kind": "explain",
        "title": "Same idea, gigantic scale 🎉",
        "body": "You just built and trained a real neuron — drew its boundary, watched it fix its own weights, then trained a fresh one solo. That exact loop, with **billions** of weights and millions of dots, is what powers the chatbots and image apps you've heard about.\n\nOne last thing: a single neuron can only draw **one straight line**. Some groups can't be split that way — they need a *curve*. The fix is to wire **many** neurons together into a **network**, and their simple lines combine into curves.\n\n**Next up:** see this same idea make *words* — train a tiny language model in **How AI writes**."
      }
    ]
  },
  "how-ai-writes": {
    "manifest": {
      "id": "how-ai-writes",
      "title": "How AI writes",
      "blurb": "Train your own tiny ChatGPT. Feed it text, watch it learn to guess the next word, then make it write.",
      "level": "advanced",
      "estMinutes": 13,
      "icon": "Bot",
      "concept": "language models",
      "order": 7
    },
    "steps": [
      {
        "kind": "explain",
        "title": "The magic trick behind ChatGPT",
        "body": "Chatbots can write stories, answer questions, even rhyme. It feels like magic.\n\nBut the secret is almost silly: a chatbot is just **guessing the next word**, over and over. Say a few words, and it asks itself *\"what word usually comes next?\"* — picks one — then does it again. That's it. You're about to build the smallest possible version and see for yourself."
      },
      {
        "kind": "explain",
        "title": "Words become tokens",
        "body": "Before an AI can work with language, it chops the text into little pieces called **tokens**. For us, a token is just a **word** (and punctuation like `.` or `?`).\n\n\"the cat sat\" → `the` · `cat` · `sat`. Simple. Now the AI can count which tokens tend to follow which."
      },
      {
        "kind": "explain",
        "title": "Predict the next word",
        "body": "Here's the whole idea. The model reads a lot of text and keeps a tally:\n\nAfter **\"the cat\"**, what came next? Maybe `sat` 5 times, `ran` 2 times, `is` 1 time.\n\nSo when you give it \"the cat\", it knows `sat` is the most likely next word. **Training** is just building that tally — no magic, just counting."
      },
      {
        "kind": "explain",
        "title": "How far back does it look?",
        "body": "The **context window** is how many previous words the model looks at to make its guess.\n\nLook back **1 word** and it barely makes sense. Look back **3 words** and it sounds much smoother — but on a little bit of text it starts to just **memorize and repeat**. Real LLMs look back over *thousands* of tokens. You'll get to slide this and feel the difference."
      },
      {
        "kind": "widget",
        "widget": "langModel",
        "title": "Train it and make it write",
        "body": "1) Pick some text and press **Train it**. 2) Peek at the **next-word table** — that's literally what it learned. 3) Type a start and press **Generate**.\n\nThen play: change **Look back** (1 → 3 words) and re-train. Watch the writing get smoother but more repetitive.",
        "config": {
          "corpus": "rhymes",
          "contextWindow": 2
        }
      },
      {
        "kind": "quiz",
        "title": "What is it really doing?",
        "question": "When a language model writes a sentence, what is it actually doing at each step?",
        "choices": [
          "Looking up the answer in a dictionary",
          "Guessing the next word, then repeating",
          "Copying a random website",
          "Asking a human what to say"
        ],
        "answer": 1,
        "explain": "Every word is a next-word guess based on the words so far. Do that again and again and you get whole sentences."
      },
      {
        "kind": "explain",
        "title": "Creativity = temperature",
        "body": "When several words could come next, how does it choose? That's the **creativity** knob (pros call it *temperature*).\n\n**Careful**: it almost always picks the single most likely word — safe but repetitive. **Wild**: it takes more chances on less-likely words — surprising, sometimes nonsense. Slide it and watch the next-word table change shape."
      },
      {
        "kind": "widget",
        "widget": "langModel",
        "title": "Play with creativity",
        "body": "Train it, then move the **Creativity** slider and Generate a few times. Low = it repeats the safe path. High = it wanders. Notice the next-word percentages flatten out as you turn creativity up.",
        "config": {
          "corpus": "fables",
          "contextWindow": 2,
          "temperature": 0.9
        }
      },
      {
        "kind": "quiz",
        "title": "Turning up creativity",
        "question": "If you turn the creativity (temperature) way up, what happens?",
        "choices": [
          "It always picks the most likely word",
          "It takes more chances on less-likely words, so output is more surprising",
          "It stops working",
          "It looks back at more words"
        ],
        "answer": 1,
        "explain": "High creativity flattens the odds so unlikely words get picked more often — fun, but it can drift into nonsense."
      },
      {
        "kind": "quiz",
        "title": "So what is 'training'?",
        "question": "You trained your model. What did training actually build?",
        "choices": [
          "A picture of a robot",
          "A tally of which words tend to follow which",
          "A list of websites",
          "A new programming language"
        ],
        "answer": 1,
        "explain": "Training = counting patterns (which word follows which). Real LLMs store this as billions of weights, but it's the same idea you just did."
      },
      {
        "kind": "explain",
        "title": "Same idea, gigantic scale",
        "body": "You just built a real language model: tokens, next-word prediction, a context window, and a creativity knob.\n\nChatGPT is the **exact same recipe** — scaled up almost unimaginably. Instead of a few rhymes it read much of the internet; instead of a tally it uses a giant neural network with billions of weights (the same weights you tuned in *How a brain learns*). But peek inside and it's doing what your tiny model just did: **guess the next word, then repeat**. You now understand how AI writes. 🎉"
      }
    ]
  },
  "predicting-numbers": {
    "manifest": {
      "id": "predicting-numbers",
      "title": "Predicting numbers",
      "blurb": "Not every answer is a category — sometimes AI predicts a number. Lay the line of best fit yourself.",
      "level": "intermediate",
      "estMinutes": 10,
      "icon": "LineChart",
      "concept": "regression",
      "order": 4
    },
    "steps": [
      {
        "kind": "explain",
        "title": "Two kinds of questions",
        "body": "So far your AIs answered **which kind?** — cat or dog, rose or daisy. That's **classification**.\n\nBut some questions don't have categories. *\"How tall will this plant grow?\"* *\"What will this house sell for?\"* The answer is a **number**. Predicting a number has its own name: **regression** — and the trick is to draw the best straight line through your examples."
      },
      {
        "kind": "widget",
        "widget": "regression",
        "title": "Lay the line yourself",
        "body": "Below are data points. **Drag the two ring handles** to lay a straight line through them. The orange dashes are the **misses**, and the **error** number is how far off you are overall. Tune it until the error drops under the goal. (Stuck? **Snap to best fit** shows the perfect line.)"
      },
      {
        "kind": "explain",
        "title": "That 'error' is how AI learns",
        "body": "Every orange dash was a **mistake** — the gap between a real dot and your line. Add them all up and you get the **error** (also called the **loss**). The best line is simply the one with the **smallest error** — that's exactly what you hunted for.\n\nPause on this, because it's huge: **learning = lowering the error.** A giant AI with billions of settings trains the same way you just did — guess, measure how wrong, adjust, repeat."
      },
      {
        "kind": "quiz",
        "title": "The learning loop",
        "question": "In one sentence, what does 'training' an AI really mean?",
        "choices": [
          "Making the error as small as possible",
          "Making the computer faster",
          "Adding more colors",
          "Turning it off and on"
        ],
        "answer": 0,
        "explain": "Exactly — training means adjusting the model until the error is as small as it can be. You just did it by hand."
      },
      {
        "kind": "explain",
        "title": "The overfitting trap",
        "body": "You *could* draw a wild, wiggly line that hits **every** dot perfectly… but that's usually a trap. A line that bends to touch every dot has **memorized** the examples instead of learning the pattern — give it a new dot and it flails. That's **overfitting**.\n\nWant to feel it? The **Regression Studio** lets you crank the curve from straight to super-bendy and watch it overfit on purpose."
      },
      {
        "kind": "explain",
        "title": "What you built 🎉",
        "body": "- **Classification** predicts a category; **regression** predicts a **number**\n- You laid the **line of best fit** — the one with the smallest **error (loss)**\n- **Training = lowering the error**, step by step — the heart of all AI\n- A simple line that's 'close enough' usually beats a wiggly one that **overfits**\n\n**Next up:** a different kind of AI you can actually *read* — the **decision tree**."
      }
    ]
  },
  "train-your-first-ai": {
    "manifest": {
      "id": "train-your-first-ai",
      "title": "Train your first AI",
      "blurb": "Teach a computer to tell two things apart — using your own camera. No code.",
      "level": "beginner",
      "estMinutes": 10,
      "icon": "Sparkles",
      "concept": "classification",
      "order": 3
    },
    "steps": [
      {
        "kind": "explain",
        "title": "What does it mean to *train* an AI?",
        "body": "An AI doesn't come knowing things. You **teach** it — by showing it examples, over and over, until it spots the pattern itself.\n\nThat's it. That's the whole secret. You're about to teach a real AI to tell two things apart, just by showing it pictures. Let's go."
      },
      {
        "kind": "explain",
        "title": "Remember: examples are data",
        "body": "In the last lesson you learned AI runs on **data**. Well — the example photos you're about to take *are* the data, and each photo's features (its colors and shapes) are what the AI learns from.\n\nSo keep the golden rule in mind: give it **plenty of clear, balanced** examples of each thing, and it'll be smart. Skimp, and it'll be biased."
      },
      {
        "kind": "widget",
        "widget": "classifier",
        "title": "Show it some examples",
        "body": "Pick two things to tell apart — like ✌️ vs 👍, or a pen vs your hand. Add a bunch of example photos of each, then press **Train**. Watch how sure it gets — that's it *learning*.",
        "config": {
          "classes": [
            "Thing A",
            "Thing B"
          ]
        }
      },
      {
        "kind": "quiz",
        "title": "Quick check",
        "question": "How did your AI know what each thing looked like?",
        "choices": [
          "It already knew",
          "From the example photos you showed it",
          "It guessed randomly",
          "It looked it up online"
        ],
        "answer": 1,
        "explain": "Exactly — it learned **only** from the examples you gave it. More (and better) examples make a smarter model."
      },
      {
        "kind": "explain",
        "title": "Why does it sometimes get things wrong?",
        "body": "If you showed it 3 photos of one thing and 30 of the other, it gets **lopsided** — it leans toward whatever it saw most. That's called **bias**, and it's one of the most important ideas in all of AI.\n\nGo back and add more examples of the thing it keeps missing — then watch it get better. *You* are making it smarter."
      },
      {
        "kind": "quiz",
        "title": "Last one",
        "question": "Your AI keeps guessing \"Thing B.\" What's the most likely fix?",
        "choices": [
          "Add more examples of Thing A",
          "Turn it off and on again",
          "Nothing — AIs are just like that",
          "Ask it nicely"
        ],
        "answer": 0,
        "explain": "Right — a model that always picks one answer usually hasn't seen enough of the *other* one. Balance your examples and it evens out."
      }
    ]
  },
  "what-is-ai": {
    "manifest": {
      "id": "what-is-ai",
      "title": "What even is AI?",
      "blurb": "Cut through the hype — what AI really is, where you already use it, and why it's not magic.",
      "level": "beginner",
      "estMinutes": 12,
      "icon": "Brain",
      "concept": "intro",
      "order": 1
    },
    "steps": [
      {
        "kind": "explain",
        "title": "AI is everywhere — but what *is* it?",
        "body": "You've heard \"AI\" a hundred times. It unlocks your phone with your face, suggests the next video, finishes your sentences.\n\nBut here's a secret: almost nobody can explain what it actually **is**. By the end of this lesson, you will — and you'll even train a tiny one yourself."
      },
      {
        "kind": "explain",
        "title": "The one-sentence answer",
        "body": "**AI is a computer program that learns from examples instead of being told exactly what to do.**\n\nNormal programs follow rules a human wrote: \"if the light is red, stop.\" An AI is different — you show it **lots of examples**, and it figures out the pattern on its own."
      },
      {
        "kind": "explain",
        "title": "An example you already get",
        "body": "Imagine teaching a little kid the difference between a cat and a dog. You don't hand them a rulebook. You just point at animals: *\"cat… dog… cat… dog…\"*\n\nAfter enough examples, the kid just **knows**. AI learns the exact same way — from examples, not rules."
      },
      {
        "kind": "quiz",
        "title": "Quick check",
        "question": "What's the big difference between AI and a normal computer program?",
        "choices": [
          "AI is always right",
          "AI learns patterns from examples instead of following written rules",
          "AI is alive",
          "AI never needs a computer"
        ],
        "answer": 1,
        "explain": "That's it — AI learns the pattern from examples. A normal program just follows rules a person wrote out."
      },
      {
        "kind": "explain",
        "title": "What AI is NOT",
        "body": "Let's bust three myths right now:\n\n- ❌ **It's not magic.** It's math and examples — a lot of them.\n- ❌ **It's not a person.** It doesn't *understand* or *feel* anything. It finds patterns.\n- ❌ **It's not always right.** It can be confidently wrong (you'll see why soon)."
      },
      {
        "kind": "quiz",
        "title": "Myth check",
        "question": "True or false: an AI *understands* the world the way a human does.",
        "choices": [
          "True",
          "False"
        ],
        "answer": 1,
        "explain": "False! AI is a brilliant **pattern-spotter**, but it doesn't understand meaning like you do. That's an important difference to remember."
      },
      {
        "kind": "explain",
        "title": "How learning actually works",
        "body": "Every AI does three things:\n\n1. **See examples** (lots of cat and dog photos)\n2. **Find the pattern** (cats have pointy ears, dogs are bigger…)\n3. **Make a guess** on something new (\"that's probably a cat\")\n\nMore examples → better patterns → better guesses. Simple as that."
      },
      {
        "kind": "explain",
        "title": "Where you already meet AI",
        "body": "You use AI all day without noticing:\n\n- 📷 Your photos app finding every picture of your dog\n- 🎵 \"Songs you might like\"\n- 🗣️ Voice assistants understanding what you said\n- ✍️ Autocorrect and text suggestions\n\nEach one learned from millions of examples."
      },
      {
        "kind": "quiz",
        "title": "Spot the AI",
        "question": "Which of these most likely uses AI?",
        "choices": [
          "A calculator adding 2 + 2",
          "A light switch turning on a bulb",
          "Your phone recognizing your face to unlock",
          "A clock showing the time"
        ],
        "answer": 2,
        "explain": "Face unlock learned from many face examples — that's AI. The others just follow fixed rules."
      },
      {
        "kind": "explain",
        "title": "Why AI gets things wrong",
        "body": "An AI is only as good as the examples it learned from.\n\nIf it only ever saw small dogs, it might call a *horse* a dog. It didn't \"think\" wrong — it just never saw the right examples. **Garbage in, garbage out.** Keep this idea in your pocket; it explains almost every AI mistake."
      },
      {
        "kind": "quiz",
        "title": "Why the mistake?",
        "question": "An AI keeps calling a wolf a \"dog.\" What's the most likely reason?",
        "choices": [
          "The AI is broken",
          "It never learned from enough wolf examples",
          "Wolves and dogs are the same",
          "The computer is too slow"
        ],
        "answer": 1,
        "explain": "Right — it learned from dog examples and never really saw wolves, so it guesses the closest thing it knows."
      },
      {
        "kind": "explain",
        "title": "Your turn — teach a real one",
        "body": "Enough talk. You're going to **train an actual AI** right now, in your browser, using your camera.\n\nPick two things to tell apart, show it a few examples of each, and watch it learn. This is the exact same idea behind the biggest AI systems in the world — just smaller."
      },
      {
        "kind": "widget",
        "widget": "classifier",
        "title": "Train a tiny AI",
        "body": "Add a few example photos of two different things (like ✌️ vs 👍), then press **Train it!** and test it live.",
        "config": {
          "classes": [
            "Thing A",
            "Thing B"
          ]
        }
      },
      {
        "kind": "explain",
        "title": "What you just did",
        "body": "You showed an AI examples, it found the pattern, and it made guesses. **That's the whole game** — whether it's your tiny classifier or a giant model that writes essays.\n\nThe big ones just have *way* more examples and *way* more computing power. The core idea is identical."
      },
      {
        "kind": "quiz",
        "title": "Lock it in",
        "question": "What's the single most important ingredient for teaching an AI?",
        "choices": [
          "A faster computer",
          "Good examples to learn from",
          "A bigger screen",
          "Luck"
        ],
        "answer": 1,
        "explain": "Examples are everything. Good, plentiful, balanced examples make a smart AI — which is exactly what the next lesson is all about: **data**."
      },
      {
        "kind": "explain",
        "title": "What you learned 🎉",
        "body": "- AI **learns from examples**, not written rules\n- It's a pattern-spotter — **not magic, not a person, not always right**\n- It gets things wrong when its examples were missing or unfair\n- You **trained a real one yourself!**\n\n**Next up:** where all those examples come from — *data* — and why good data is the secret to good AI."
      }
    ]
  }
};

export const LESSON_IDS: string[] = Object.keys(LESSONS);
