// AUTO-GENERATED by scripts/gen-lessons.mjs — do not edit by hand.
// Run `npm run gen:lessons` after changing anything under lessons/.
import type { Lesson } from "./types";

export const LESSONS: Record<string, Lesson> = {
  "data-and-features": {
    "manifest": {
      "id": "data-and-features",
      "title": "Data is everything",
      "blurb": "AI learns from data — pick the right measurements and make the first cut that separates the kinds.",
      "level": "beginner",
      "estMinutes": 10,
      "icon": "Boxes",
      "concept": "data",
      "order": 2
    },
    "steps": [
      {
        "kind": "explain",
        "title": "What data looks like",
        "body": "An AI learns from a big pile of **examples** — that's **data**, usually just a **table**. Each **row** is one example (one penguin, one photo). Each **column** is one thing we measured.\n\nTwo words pros use constantly:\n- **Features** = the things we *measure* (a penguin's bill length, flipper length…).\n- **Label** = the *answer* we want (which kind of penguin it is).\n\nThe AI's job: look at the **features** and guess the **label**."
      },
      {
        "kind": "widget",
        "widget": "dataExplorer",
        "title": "Make the first cut",
        "body": "Here are two kinds of penguin with three measurements each. Put measurements on the **X** and **Y** axes, then **drag the divider** to split the two kinds apart. Find the measurements + cut that separate them best — aim for 90%.",
        "config": {
          "dataset": "penguins"
        }
      },
      {
        "kind": "explain",
        "title": "Good features do the work",
        "body": "Notice how **some measurements separated the penguins cleanly** and others left the colors all mixed up? Picking **good features** is half the battle in real AI.\n\nIt's like guessing someone's favorite sport: their *height* helps a little, but \"do they own a soccer ball?\" helps a lot more. With the right features, a single cut already does most of the job — that's the seed of every classifier."
      },
      {
        "kind": "explain",
        "title": "Garbage in, garbage out — and bias",
        "body": "Here's the rule behind most AI failures: **an AI can only be as good as its data.** Messy or lopsided data → a confused AI.\n\nImagine training on **100 of one kind and 4 of the other**. The AI barely sees the rare kind, so it just guesses the common one — not because it's smart, but because that's mostly what it *saw*. That lopsidedness has a name: **bias**, and it comes from the data we collect, not the computer."
      },
      {
        "kind": "quiz",
        "title": "Spot the bias",
        "question": "An AI that sorts fruit was trained on 100 apples and 4 bananas. What will probably happen?",
        "choices": [
          "It works perfectly",
          "It leans toward guessing 'apple' because that's mostly what it saw",
          "It refuses to run",
          "It prefers bananas"
        ],
        "answer": 1,
        "explain": "Exactly — a lopsided dataset makes a lopsided AI. Balanced, fair examples are the fix, and that's one of the most important jobs in real AI."
      },
      {
        "kind": "explain",
        "title": "What you learned 🎉",
        "body": "- **Data** = a table of examples with **features** (what we measure) and a **label** (the answer)\n- **Good features** make the kinds separate — you found them and cut them apart yourself\n- **Garbage in, garbage out** — data quality beats computer speed\n- **Bias** is born from lopsided data; **balanced, fair data** is the cure\n\n**Next up:** instead of sorting into kinds, you'll teach an AI to **predict a number** — that's *regression*."
      }
    ]
  },
  "decision-trees": {
    "manifest": {
      "id": "decision-trees",
      "title": "Decision trees",
      "blurb": "An AI you can actually read — grow a tree of yes/no questions and watch it sort a pile of pets.",
      "level": "intermediate",
      "estMinutes": 11,
      "icon": "GitBranch",
      "concept": "trees",
      "order": 5
    },
    "steps": [
      {
        "kind": "explain",
        "title": "The AI you can read",
        "body": "Some AIs are a mystery box — they give an answer but can't explain *why*.\n\nA **decision tree** is the opposite. It sorts things with a chain of simple **yes/no questions**, like a game of 20 Questions. Each question is a **split** that cuts a pile into two. You're about to grow one yourself."
      },
      {
        "kind": "widget",
        "widget": "tree",
        "title": "Grow your tree",
        "body": "Here's a pile of pets — cats, dogs and rabbits — with their weight, ear length and tail length. **Click a leaf**, pick a measurement and a cut, and **Add split**. Keep splitting the messy leaves until your tree sorts almost all of them. Watch the accuracy climb!",
        "config": {
          "dataset": "creatures"
        }
      },
      {
        "kind": "explain",
        "title": "Look what you did",
        "body": "Notice how **one split was never enough** — you had to keep asking another question on each side, and the tree got deeper and smarter. That branching shape is exactly why it's called a *tree*.\n\nAnd each split you added split the pile a little **cleaner** — that's the whole game: a tree always hunts for the question that separates the groups best."
      },
      {
        "kind": "explain",
        "title": "Its superpower: you can explain it",
        "body": "Here's what makes trees special. If your tree says *\"this is a rabbit,\"* it can show exactly **why**: *\"because its tail was short, and it was light.\"* You can read the path.\n\nThat's called being **explainable** (a \"white box\"). Doctors, banks and judges love trees for this — when an AI affects someone's life, being able to explain the *why* really matters."
      },
      {
        "kind": "quiz",
        "title": "Why trees?",
        "question": "Why might a hospital prefer a decision tree over a mystery-box AI?",
        "choices": [
          "It's prettier",
          "You can see and explain exactly why it made each decision",
          "It needs no data",
          "It's always 100% correct"
        ],
        "answer": 1,
        "explain": "Explainability! A tree shows its reasoning step by step — crucial when a decision affects a real person."
      },
      {
        "kind": "explain",
        "title": "What you built 🎉",
        "body": "You grew a real decision tree:\n\n- It sorts things with a chain of **yes/no questions** (splits)\n- **More branches = smarter** — one split is rarely enough\n- Each split aims to separate the groups **cleanest**\n- Its superpower is being **explainable** — it can always show its reasoning\n\nWant to go deeper? The **Decision Tree Studio** has the same build with a held-out test set, so you can watch *overfitting* happen. **Next up:** neural networks — teach a tiny digital 'brain' to learn."
      }
    ]
  },
  "how-a-brain-learns": {
    "manifest": {
      "id": "how-a-brain-learns",
      "title": "How a neuron learns",
      "blurb": "Sort pets, draw a line, then watch a real neuron tune itself — round by round — until it beats you.",
      "level": "beginner",
      "estMinutes": 28,
      "icon": "Brain",
      "concept": "neural networks",
      "order": 6,
      "objectives": [
        "What a neuron really is — a line that splits things into two groups",
        "What its two knobs (weights & bias) actually do",
        "How it fixes its own line by learning from mistakes, one round at a time",
        "How to tell if it really LEARNED — or just memorized",
        "Why one neuron isn't enough, and where networks come from"
      ],
      "glossary": [
        {
          "term": "Neuron",
          "def": "The tiniest part of an AI brain. From two clues it makes one call — by drawing a line."
        },
        {
          "term": "Decision boundary",
          "def": "The line a neuron draws. One side is one group, the other side is the other."
        },
        {
          "term": "Weights",
          "def": "The dials that tilt the line — how much each clue matters."
        },
        {
          "term": "Bias",
          "def": "The dial that slides the line up or down without tilting it — the tipping point."
        },
        {
          "term": "Error",
          "def": "How many it got wrong. Learning means making the error smaller."
        },
        {
          "term": "Round",
          "def": "One pass where the neuron checks its mistakes and nudges its dials a little."
        },
        {
          "term": "Training",
          "def": "Repeating rounds — check mistakes, nudge, repeat — until it's good."
        },
        {
          "term": "Generalize",
          "def": "Doing well on NEW examples it never studied. That's real learning, not memorizing."
        },
        {
          "term": "Network",
          "def": "Many neurons wired together, so their straight lines combine into curves."
        }
      ]
    },
    "steps": [
      {
        "kind": "explain",
        "title": "Part 1 · A robot that sorts pets",
        "body": "Meet a robot with one job: look at a pet and say **cat or dog**. It can't see fur or hear barks — it only gets two clues: **ear size** and **tail length**.\n\nThat's it. From two numbers, it has to decide. Sounds hard? You're about to do it yourself first."
      },
      {
        "kind": "widget",
        "widget": "sortGame",
        "title": "You be the AI",
        "body": "Here are some pets, each with its two clues shown as bars. Sort every one into **Cat** or **Dog**. Trust the clues!",
        "youWillDo": "sort the pets yourself, using the clues",
        "config": {
          "dataset": "boundary"
        }
      },
      {
        "kind": "predict",
        "title": "A quick guess",
        "prompt": "If we put every pet on a chart — ear size across, tail length up — do you think **one straight line** could keep most cats on one side and dogs on the other?",
        "choices": [
          "Yes, one straight line could split most of them",
          "No, you'd need a curvy line",
          "Not sure yet"
        ],
        "afterPick": "Hold that thought — you'll draw the line yourself next. →",
        "youWillDo": "make a prediction"
      },
      {
        "kind": "widget",
        "widget": "neuronBoundary",
        "title": "Draw the line",
        "body": "Drag the two purple dots to swing the line until cats and dogs are on different sides. Get **wrong** as low as you can, then **Lock in**.",
        "youWillDo": "drag the line to split cats from dogs",
        "config": {
          "phase": "explore",
          "dataset": "boundary"
        }
      },
      {
        "kind": "explain",
        "title": "So close — but not perfect",
        "body": "You probably got *most* of them, but a few stubborn dots stayed on the wrong side. The groups overlap a little, and a line placed **by hand** can only do so much.\n\nSo how could the robot do better than your best try? That's the whole rest of this lesson. First, let's look *inside* the line."
      },
      {
        "kind": "explain",
        "title": "Part 2 · What's inside the line",
        "body": "That line isn't magic — it's run by just **two kinds of dial**:\n\n- **Weights** — how much each clue *matters*. They **tilt** the line.\n- **Bias** — the **tipping point**. It **slides** the line up or down.\n\nLet's grab the dials and feel what each one does."
      },
      {
        "kind": "predict",
        "title": "Which dial?",
        "prompt": "You want to make the line **tilt** to a new angle. Which dial should you turn?",
        "choices": [
          "A weight",
          "The bias",
          "Neither — you can't tilt it"
        ],
        "afterPick": "Let's test it on a real neuron. →",
        "youWillDo": "predict which dial tilts the line"
      },
      {
        "kind": "widget",
        "widget": "neuronSchematic",
        "title": "Turn the dials",
        "body": "This is the inside of a neuron. The two clues go in, get multiplied by the **weights**, plus a **bias**, and the total decides the answer. Drag the dials and watch the answer flip — and the math change live.",
        "youWillDo": "drag the weight & bias dials and watch the output flip",
        "config": {
          "dataset": "boundary"
        }
      },
      {
        "kind": "quiz",
        "title": "Check yourself",
        "question": "Which dial slides the line up or down **without** tilting it?",
        "choices": [
          "A weight",
          "The bias",
          "The ear-size clue",
          "None of them"
        ],
        "answer": 1,
        "explain": "Right — the **bias** is the tipping point. It moves the line without changing its angle. Weights change the angle."
      },
      {
        "kind": "explain",
        "title": "Part 3 · Counting mistakes",
        "body": "To get *better*, the neuron first needs to know how *wrong* it is. So it counts: how many pets are on the wrong side of the line right now? That count is called the **error**.\n\nLearning has one goal: make the error smaller."
      },
      {
        "kind": "predict",
        "title": "Guess the shape",
        "prompt": "Each round, the neuron nudges its line a little toward the dots it got wrong. If it keeps doing that, what happens to the number of mistakes?",
        "choices": [
          "It drops, round after round",
          "It stays the same",
          "It goes up"
        ],
        "afterPick": "Let's watch it as a chart. →",
        "youWillDo": "predict what the mistakes will do"
      },
      {
        "kind": "widget",
        "widget": "errorChart",
        "title": "Watch the mistakes fall",
        "body": "Press **Train a round** (or **Auto**). Each bar is how many mistakes the neuron still makes after that round. Watch the bars shrink.",
        "youWillDo": "train rounds and watch the mistake bars drop",
        "config": {
          "dataset": "boundary"
        }
      },
      {
        "kind": "reflect",
        "title": "Say it your way",
        "prompt": "In your own words, what does **error** mean for the neuron — and what does it want to do with it?",
        "placeholder": "Error is… and the neuron tries to…",
        "recall": {
          "question": "What is the neuron's goal each round?",
          "choices": [
            "Make the error (mistakes) bigger",
            "Make the error smaller",
            "Keep the error exactly the same",
            "Ignore the error"
          ],
          "answer": 1,
          "explain": "Yes — every round it nudges toward making fewer mistakes. Smaller error = better."
        },
        "youWillDo": "explain what 'error' means"
      },
      {
        "kind": "explain",
        "title": "Part 4 · One nudge at a time",
        "body": "Here's the trick that makes it all work. The neuron doesn't guess once — it **repeats a round**: look at the mistakes, nudge the dials a tiny bit, check again. Over and over.\n\nLet's do it one round at a time so you can see each nudge."
      },
      {
        "kind": "widget",
        "widget": "neuronBoundary",
        "title": "Run it one round at a time",
        "body": "Press **Run one round**. Each press, the neuron looks at its mistakes and nudges the line a little. Watch the **wrong** count drop, press by press.",
        "youWillDo": "press Run one round and watch each nudge",
        "config": {
          "phase": "step",
          "dataset": "boundary"
        }
      },
      {
        "kind": "explain",
        "title": "It has real names now",
        "body": "What you just did has names — and now they'll stick:\n\n- The line is the **decision boundary**.\n- The dials that move it are the **weights** (and bias).\n- **Learning** = nudging those dials a little after each mistake, round after round.\n\nThat's the whole secret. Now watch it run full speed."
      },
      {
        "kind": "widget",
        "widget": "neuronBoundary",
        "title": "Same thing, sped up",
        "body": "Press **Watch it learn**. It starts from a bad line on purpose, then runs the same rounds automatically — wrong dots flash, the line tunes itself.",
        "youWillDo": "watch the neuron tune its own line fast",
        "config": {
          "phase": "reveal",
          "dataset": "boundary"
        }
      },
      {
        "kind": "quiz",
        "title": "Quick check",
        "question": "When the neuron \"learns,\" what is actually changing each round?",
        "choices": [
          "The dots move",
          "Its weights & bias (the dials)",
          "The colors",
          "Nothing"
        ],
        "answer": 1,
        "explain": "The dots never change — the **dials** do. Moving the weights and bias is exactly what learning is."
      },
      {
        "kind": "explain",
        "title": "Part 5 · Did it really learn — or memorize?",
        "body": "Here's a sneaky question. The neuron got great at the pets it practiced on. But did it learn the *idea* of cat-vs-dog… or did it just memorize those exact pets?\n\nThere's one way to find out: show it **brand-new pets it has never seen**."
      },
      {
        "kind": "predict",
        "title": "Your call",
        "prompt": "The neuron aced the pets it studied. How will it do on totally new pets it never trained on?",
        "choices": [
          "Just as well — it learned the idea",
          "Much worse — it only memorized",
          "No way to ever tell"
        ],
        "afterPick": "Let's actually test it. The new pets are the hollow dots. →",
        "youWillDo": "predict how it does on new pets"
      },
      {
        "kind": "widget",
        "widget": "neuronBoundary",
        "title": "The real test",
        "body": "The **hollow** dots are new pets — the neuron never sees them while training. Press **Train on the studied pets**, then check its score on the new ones.",
        "youWillDo": "train, then check the NEW (hollow) pets",
        "config": {
          "phase": "generalize",
          "dataset": "boundary"
        }
      },
      {
        "kind": "explain",
        "title": "That's called generalizing",
        "body": "It did well on pets it had **never seen**. That means it didn't memorize — it learned the real pattern. Doing well on new examples is called **generalizing**, and it's the whole point of learning.\n\n(If it had aced the studied pets but flopped on new ones, that's **memorizing** — and it's a trap real AI engineers watch out for.)"
      },
      {
        "kind": "reflect",
        "title": "Make it yours",
        "prompt": "Why do we test the neuron on **new** pets instead of the ones it already practiced on?",
        "placeholder": "Because if we only tested the practice ones…",
        "recall": {
          "question": "A neuron scores 100% on its practice pets but only 55% on new ones. What happened?",
          "choices": [
            "It generalized well",
            "It memorized instead of learning",
            "It had no weights",
            "New pets are impossible"
          ],
          "answer": 1,
          "explain": "Exactly — acing practice but failing new ones means it memorized, not learned. Real learning shows up on new examples."
        },
        "youWillDo": "explain why we test on new examples"
      },
      {
        "kind": "explain",
        "title": "Part 6 · Train one yourself",
        "body": "You've seen every piece: clues in, a line, dials, rounds, and the real test. Time to put it together and train a neuron **from scratch**, with no hints."
      },
      {
        "kind": "widget",
        "widget": "neuronBoundary",
        "title": "Your neuron",
        "body": "New pets, no hints. Set a rough line with the dots, then press **Train my neuron** and watch it finish the job on its own.",
        "youWillDo": "set a line, then train your own neuron",
        "config": {
          "phase": "youdo",
          "dataset": "boundaryEasy"
        }
      },
      {
        "kind": "quiz",
        "title": "The whole loop",
        "question": "Put it together — how does a neuron learn?",
        "choices": [
          "It memorizes every example perfectly",
          "Guess → count mistakes → nudge the dials → repeat",
          "It asks a human for the answer each time",
          "It picks the dials randomly and hopes"
        ],
        "answer": 1,
        "explain": "That loop — guess, check, nudge, repeat — is the heartbeat of every AI, from this tiny neuron to the biggest models."
      },
      {
        "kind": "explain",
        "title": "Part 7 · Some shapes one line can't cut",
        "body": "One neuron draws **one straight line**. That's perfect for two tidy groups — but the world isn't always tidy.\n\nWhat if one group is *wrapped around* the other, like a ring around its center? Let's see if a straight line can handle that."
      },
      {
        "kind": "predict",
        "title": "Can it be done?",
        "prompt": "Can a single **straight line** separate a ring of dots from the cluster in its center?",
        "choices": [
          "Yes, at the right angle",
          "No — a straight line can't wrap around",
          "Only if you tilt it a lot"
        ],
        "afterPick": "Let the neuron try as hard as it can. →",
        "youWillDo": "predict if one line can split a ring"
      },
      {
        "kind": "widget",
        "widget": "neuronBoundary",
        "title": "Let it try the ring",
        "body": "Now the dots make a **ring** around a core. Press **Let it try** and watch — no matter how the neuron tilts its line, it gets stuck.",
        "youWillDo": "let the neuron try (and watch it get stuck)",
        "config": {
          "phase": "fail",
          "dataset": "ring"
        }
      },
      {
        "kind": "explain",
        "title": "So we use more neurons",
        "body": "One straight line can't wrap a ring — it plateaus, stuck. That's not a failure; it's the reason **networks** exist.\n\nWire **many** neurons together and their straight lines **combine into curves**. Stack enough and they can separate almost any shape. That's the *deep* in \"deep learning.\""
      },
      {
        "kind": "reflect",
        "title": "One last time, in your words",
        "prompt": "Pretend a friend asks: *\"How does a neuron learn?\"* Explain it the way you'd tell them.",
        "placeholder": "A neuron is basically a line, and it learns by…",
        "recall": {
          "question": "Which sentence best sums up how a neuron learns?",
          "choices": [
            "It draws a line, then nudges its dials after each mistake until it makes few mistakes",
            "It memorizes the answer to every example",
            "It waits for a human to set the perfect line",
            "It guesses once and never changes"
          ],
          "answer": 0,
          "explain": "That's it — a line, plus the nudge-after-mistakes loop. You now understand the core of every neural network."
        },
        "youWillDo": "explain a neuron in your own words"
      },
      {
        "kind": "explain",
        "title": "What you built today 🎉",
        "body": "You sorted pets, drew a boundary, turned a neuron's dials, watched its mistakes fall, trained one from scratch, proved it really learned, and found the exact spot where one neuron needs help.\n\nThat's the real foundation of AI — the same idea runs the chatbots and image apps you've heard of, just with billions of dials.\n\n**Next up:** see this idea make *words* — train a tiny language model in **How AI writes**."
      }
    ]
  },
  "how-ai-writes": {
    "manifest": {
      "id": "how-ai-writes",
      "title": "How AI writes",
      "blurb": "Train your own tiny ChatGPT. Feed it text, watch it learn to guess the next word, then make it write.",
      "level": "advanced",
      "estMinutes": 13,
      "icon": "Bot",
      "concept": "language models",
      "order": 7
    },
    "steps": [
      {
        "kind": "explain",
        "title": "The magic trick behind ChatGPT",
        "body": "Chatbots can write stories, answer questions, even rhyme. It feels like magic.\n\nBut the secret is almost silly: a chatbot is just **guessing the next word**, over and over. Say a few words, and it asks itself *\"what word usually comes next?\"* — picks one — then does it again. That's it. You're about to build the smallest possible version and see for yourself."
      },
      {
        "kind": "explain",
        "title": "Words become tokens",
        "body": "Before an AI can work with language, it chops the text into little pieces called **tokens**. For us, a token is just a **word** (and punctuation like `.` or `?`).\n\n\"the cat sat\" → `the` · `cat` · `sat`. Simple. Now the AI can count which tokens tend to follow which."
      },
      {
        "kind": "explain",
        "title": "Predict the next word",
        "body": "Here's the whole idea. The model reads a lot of text and keeps a tally:\n\nAfter **\"the cat\"**, what came next? Maybe `sat` 5 times, `ran` 2 times, `is` 1 time.\n\nSo when you give it \"the cat\", it knows `sat` is the most likely next word. **Training** is just building that tally — no magic, just counting."
      },
      {
        "kind": "explain",
        "title": "How far back does it look?",
        "body": "The **context window** is how many previous words the model looks at to make its guess.\n\nLook back **1 word** and it barely makes sense. Look back **3 words** and it sounds much smoother — but on a little bit of text it starts to just **memorize and repeat**. Real LLMs look back over *thousands* of tokens. You'll get to slide this and feel the difference."
      },
      {
        "kind": "widget",
        "widget": "langModel",
        "title": "Train it and make it write",
        "body": "1) Pick some text and press **Train it**. 2) Peek at the **next-word table** — that's literally what it learned. 3) Type a start and press **Generate**.\n\nThen play: change **Look back** (1 → 3 words) and re-train. Watch the writing get smoother but more repetitive.",
        "config": {
          "corpus": "rhymes",
          "contextWindow": 2
        }
      },
      {
        "kind": "quiz",
        "title": "What is it really doing?",
        "question": "When a language model writes a sentence, what is it actually doing at each step?",
        "choices": [
          "Looking up the answer in a dictionary",
          "Guessing the next word, then repeating",
          "Copying a random website",
          "Asking a human what to say"
        ],
        "answer": 1,
        "explain": "Every word is a next-word guess based on the words so far. Do that again and again and you get whole sentences."
      },
      {
        "kind": "explain",
        "title": "Creativity = temperature",
        "body": "When several words could come next, how does it choose? That's the **creativity** knob (pros call it *temperature*).\n\n**Careful**: it almost always picks the single most likely word — safe but repetitive. **Wild**: it takes more chances on less-likely words — surprising, sometimes nonsense. Slide it and watch the next-word table change shape."
      },
      {
        "kind": "widget",
        "widget": "langModel",
        "title": "Play with creativity",
        "body": "Train it, then move the **Creativity** slider and Generate a few times. Low = it repeats the safe path. High = it wanders. Notice the next-word percentages flatten out as you turn creativity up.",
        "config": {
          "corpus": "fables",
          "contextWindow": 2,
          "temperature": 0.9
        }
      },
      {
        "kind": "quiz",
        "title": "Turning up creativity",
        "question": "If you turn the creativity (temperature) way up, what happens?",
        "choices": [
          "It always picks the most likely word",
          "It takes more chances on less-likely words, so output is more surprising",
          "It stops working",
          "It looks back at more words"
        ],
        "answer": 1,
        "explain": "High creativity flattens the odds so unlikely words get picked more often — fun, but it can drift into nonsense."
      },
      {
        "kind": "quiz",
        "title": "So what is 'training'?",
        "question": "You trained your model. What did training actually build?",
        "choices": [
          "A picture of a robot",
          "A tally of which words tend to follow which",
          "A list of websites",
          "A new programming language"
        ],
        "answer": 1,
        "explain": "Training = counting patterns (which word follows which). Real LLMs store this as billions of weights, but it's the same idea you just did."
      },
      {
        "kind": "explain",
        "title": "Same idea, gigantic scale",
        "body": "You just built a real language model: tokens, next-word prediction, a context window, and a creativity knob.\n\nChatGPT is the **exact same recipe** — scaled up almost unimaginably. Instead of a few rhymes it read much of the internet; instead of a tally it uses a giant neural network with billions of weights (the same weights you tuned in *How a brain learns*). But peek inside and it's doing what your tiny model just did: **guess the next word, then repeat**. You now understand how AI writes. 🎉"
      }
    ]
  },
  "predicting-numbers": {
    "manifest": {
      "id": "predicting-numbers",
      "title": "Predicting numbers",
      "blurb": "Not every answer is a category — sometimes AI predicts a number. Lay the line of best fit yourself.",
      "level": "intermediate",
      "estMinutes": 10,
      "icon": "LineChart",
      "concept": "regression",
      "order": 4
    },
    "steps": [
      {
        "kind": "explain",
        "title": "Two kinds of questions",
        "body": "So far your AIs answered **which kind?** — cat or dog, rose or daisy. That's **classification**.\n\nBut some questions don't have categories. *\"How tall will this plant grow?\"* *\"What will this house sell for?\"* The answer is a **number**. Predicting a number has its own name: **regression** — and the trick is to draw the best straight line through your examples."
      },
      {
        "kind": "widget",
        "widget": "regression",
        "title": "Lay the line yourself",
        "body": "Below are data points. **Drag the two ring handles** to lay a straight line through them. The orange dashes are the **misses**, and the **error** number is how far off you are overall. Tune it until the error drops under the goal. (Stuck? **Snap to best fit** shows the perfect line.)"
      },
      {
        "kind": "explain",
        "title": "That 'error' is how AI learns",
        "body": "Every orange dash was a **mistake** — the gap between a real dot and your line. Add them all up and you get the **error** (also called the **loss**). The best line is simply the one with the **smallest error** — that's exactly what you hunted for.\n\nPause on this, because it's huge: **learning = lowering the error.** A giant AI with billions of settings trains the same way you just did — guess, measure how wrong, adjust, repeat."
      },
      {
        "kind": "quiz",
        "title": "The learning loop",
        "question": "In one sentence, what does 'training' an AI really mean?",
        "choices": [
          "Making the error as small as possible",
          "Making the computer faster",
          "Adding more colors",
          "Turning it off and on"
        ],
        "answer": 0,
        "explain": "Exactly — training means adjusting the model until the error is as small as it can be. You just did it by hand."
      },
      {
        "kind": "explain",
        "title": "The overfitting trap",
        "body": "You *could* draw a wild, wiggly line that hits **every** dot perfectly… but that's usually a trap. A line that bends to touch every dot has **memorized** the examples instead of learning the pattern — give it a new dot and it flails. That's **overfitting**.\n\nWant to feel it? The **Regression Studio** lets you crank the curve from straight to super-bendy and watch it overfit on purpose."
      },
      {
        "kind": "explain",
        "title": "What you built 🎉",
        "body": "- **Classification** predicts a category; **regression** predicts a **number**\n- You laid the **line of best fit** — the one with the smallest **error (loss)**\n- **Training = lowering the error**, step by step — the heart of all AI\n- A simple line that's 'close enough' usually beats a wiggly one that **overfits**\n\n**Next up:** a different kind of AI you can actually *read* — the **decision tree**."
      }
    ]
  },
  "train-your-first-ai": {
    "manifest": {
      "id": "train-your-first-ai",
      "title": "Train your first AI",
      "blurb": "Teach a computer to tell two things apart — using your own camera. No code.",
      "level": "beginner",
      "estMinutes": 10,
      "icon": "Sparkles",
      "concept": "classification",
      "order": 3
    },
    "steps": [
      {
        "kind": "explain",
        "title": "What does it mean to *train* an AI?",
        "body": "An AI doesn't come knowing things. You **teach** it — by showing it examples, over and over, until it spots the pattern itself.\n\nThat's it. That's the whole secret. You're about to teach a real AI to tell two things apart, just by showing it pictures. Let's go."
      },
      {
        "kind": "explain",
        "title": "Remember: examples are data",
        "body": "In the last lesson you learned AI runs on **data**. Well — the example photos you're about to take *are* the data, and each photo's features (its colors and shapes) are what the AI learns from.\n\nSo keep the golden rule in mind: give it **plenty of clear, balanced** examples of each thing, and it'll be smart. Skimp, and it'll be biased."
      },
      {
        "kind": "widget",
        "widget": "classifier",
        "title": "Show it some examples",
        "body": "Pick two things to tell apart — like ✌️ vs 👍, or a pen vs your hand. Add a bunch of example photos of each, then press **Train**. Watch how sure it gets — that's it *learning*.",
        "config": {
          "classes": [
            "Thing A",
            "Thing B"
          ]
        }
      },
      {
        "kind": "quiz",
        "title": "Quick check",
        "question": "How did your AI know what each thing looked like?",
        "choices": [
          "It already knew",
          "From the example photos you showed it",
          "It guessed randomly",
          "It looked it up online"
        ],
        "answer": 1,
        "explain": "Exactly — it learned **only** from the examples you gave it. More (and better) examples make a smarter model."
      },
      {
        "kind": "explain",
        "title": "Why does it sometimes get things wrong?",
        "body": "If you showed it 3 photos of one thing and 30 of the other, it gets **lopsided** — it leans toward whatever it saw most. That's called **bias**, and it's one of the most important ideas in all of AI.\n\nGo back and add more examples of the thing it keeps missing — then watch it get better. *You* are making it smarter."
      },
      {
        "kind": "quiz",
        "title": "Last one",
        "question": "Your AI keeps guessing \"Thing B.\" What's the most likely fix?",
        "choices": [
          "Add more examples of Thing A",
          "Turn it off and on again",
          "Nothing — AIs are just like that",
          "Ask it nicely"
        ],
        "answer": 0,
        "explain": "Right — a model that always picks one answer usually hasn't seen enough of the *other* one. Balance your examples and it evens out."
      }
    ]
  },
  "what-is-ai": {
    "manifest": {
      "id": "what-is-ai",
      "title": "What even is AI?",
      "blurb": "Cut through the hype — what AI really is, where you already use it, and why it's not magic.",
      "level": "beginner",
      "estMinutes": 12,
      "icon": "Brain",
      "concept": "intro",
      "order": 1
    },
    "steps": [
      {
        "kind": "explain",
        "title": "AI is everywhere — but what *is* it?",
        "body": "You've heard \"AI\" a hundred times. It unlocks your phone with your face, suggests the next video, finishes your sentences.\n\nBut here's a secret: almost nobody can explain what it actually **is**. By the end of this lesson, you will — and you'll even train a tiny one yourself."
      },
      {
        "kind": "explain",
        "title": "The one-sentence answer",
        "body": "**AI is a computer program that learns from examples instead of being told exactly what to do.**\n\nNormal programs follow rules a human wrote: \"if the light is red, stop.\" An AI is different — you show it **lots of examples**, and it figures out the pattern on its own."
      },
      {
        "kind": "explain",
        "title": "An example you already get",
        "body": "Imagine teaching a little kid the difference between a cat and a dog. You don't hand them a rulebook. You just point at animals: *\"cat… dog… cat… dog…\"*\n\nAfter enough examples, the kid just **knows**. AI learns the exact same way — from examples, not rules."
      },
      {
        "kind": "quiz",
        "title": "Quick check",
        "question": "What's the big difference between AI and a normal computer program?",
        "choices": [
          "AI is always right",
          "AI learns patterns from examples instead of following written rules",
          "AI is alive",
          "AI never needs a computer"
        ],
        "answer": 1,
        "explain": "That's it — AI learns the pattern from examples. A normal program just follows rules a person wrote out."
      },
      {
        "kind": "explain",
        "title": "What AI is NOT",
        "body": "Let's bust three myths right now:\n\n- ❌ **It's not magic.** It's math and examples — a lot of them.\n- ❌ **It's not a person.** It doesn't *understand* or *feel* anything. It finds patterns.\n- ❌ **It's not always right.** It can be confidently wrong (you'll see why soon)."
      },
      {
        "kind": "quiz",
        "title": "Myth check",
        "question": "True or false: an AI *understands* the world the way a human does.",
        "choices": [
          "True",
          "False"
        ],
        "answer": 1,
        "explain": "False! AI is a brilliant **pattern-spotter**, but it doesn't understand meaning like you do. That's an important difference to remember."
      },
      {
        "kind": "explain",
        "title": "How learning actually works",
        "body": "Every AI does three things:\n\n1. **See examples** (lots of cat and dog photos)\n2. **Find the pattern** (cats have pointy ears, dogs are bigger…)\n3. **Make a guess** on something new (\"that's probably a cat\")\n\nMore examples → better patterns → better guesses. Simple as that."
      },
      {
        "kind": "explain",
        "title": "Where you already meet AI",
        "body": "You use AI all day without noticing:\n\n- 📷 Your photos app finding every picture of your dog\n- 🎵 \"Songs you might like\"\n- 🗣️ Voice assistants understanding what you said\n- ✍️ Autocorrect and text suggestions\n\nEach one learned from millions of examples."
      },
      {
        "kind": "quiz",
        "title": "Spot the AI",
        "question": "Which of these most likely uses AI?",
        "choices": [
          "A calculator adding 2 + 2",
          "A light switch turning on a bulb",
          "Your phone recognizing your face to unlock",
          "A clock showing the time"
        ],
        "answer": 2,
        "explain": "Face unlock learned from many face examples — that's AI. The others just follow fixed rules."
      },
      {
        "kind": "explain",
        "title": "Why AI gets things wrong",
        "body": "An AI is only as good as the examples it learned from.\n\nIf it only ever saw small dogs, it might call a *horse* a dog. It didn't \"think\" wrong — it just never saw the right examples. **Garbage in, garbage out.** Keep this idea in your pocket; it explains almost every AI mistake."
      },
      {
        "kind": "quiz",
        "title": "Why the mistake?",
        "question": "An AI keeps calling a wolf a \"dog.\" What's the most likely reason?",
        "choices": [
          "The AI is broken",
          "It never learned from enough wolf examples",
          "Wolves and dogs are the same",
          "The computer is too slow"
        ],
        "answer": 1,
        "explain": "Right — it learned from dog examples and never really saw wolves, so it guesses the closest thing it knows."
      },
      {
        "kind": "explain",
        "title": "Your turn — teach a real one",
        "body": "Enough talk. You're going to **train an actual AI** right now, in your browser, using your camera.\n\nPick two things to tell apart, show it a few examples of each, and watch it learn. This is the exact same idea behind the biggest AI systems in the world — just smaller."
      },
      {
        "kind": "widget",
        "widget": "classifier",
        "title": "Train a tiny AI",
        "body": "Add a few example photos of two different things (like ✌️ vs 👍), then press **Train it!** and test it live.",
        "config": {
          "classes": [
            "Thing A",
            "Thing B"
          ]
        }
      },
      {
        "kind": "explain",
        "title": "What you just did",
        "body": "You showed an AI examples, it found the pattern, and it made guesses. **That's the whole game** — whether it's your tiny classifier or a giant model that writes essays.\n\nThe big ones just have *way* more examples and *way* more computing power. The core idea is identical."
      },
      {
        "kind": "quiz",
        "title": "Lock it in",
        "question": "What's the single most important ingredient for teaching an AI?",
        "choices": [
          "A faster computer",
          "Good examples to learn from",
          "A bigger screen",
          "Luck"
        ],
        "answer": 1,
        "explain": "Examples are everything. Good, plentiful, balanced examples make a smart AI — which is exactly what the next lesson is all about: **data**."
      },
      {
        "kind": "explain",
        "title": "What you learned 🎉",
        "body": "- AI **learns from examples**, not written rules\n- It's a pattern-spotter — **not magic, not a person, not always right**\n- It gets things wrong when its examples were missing or unfair\n- You **trained a real one yourself!**\n\n**Next up:** where all those examples come from — *data* — and why good data is the secret to good AI."
      }
    ]
  }
};

export const LESSON_IDS: string[] = Object.keys(LESSONS);
